import { ArrowRight, Globe2, HeartHandshake, Lightbulb, Network, Sprout, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import ImageWithFallback from '../common/ImageWithFallback'

const story = [{title:'একটি মানবিক চিন্তার সূচনা',icon:Lightbulb},{title:'স্থানীয় ও প্রবাসীদের সংযোগ',icon:Network},{title:'সম্মিলিত সামাজিক উদ্যোগ',icon:HeartHandshake},{title:'ভবিষ্যতের জন্য সুসংগঠিত পথচলা',icon:Sprout}]
export function WhoWeAre({ settings }) {
  const org=settings.organization ?? {}; const description=org.aboutSummary || org.shortDescription || 'বাকপুরা প্রবাসী ও যুব কল্যাণ সংগঠন একটি মানবিক ও সামাজিক কল্যাণমুখী প্ল্যাটফর্ম, যেখানে স্থানীয় ও প্রবাসী বাকপুরাবাসীরা সমাজের উন্নয়ন ও মানুষের পাশে দাঁড়ানোর লক্ষ্যে একসাথে কাজ করেন।'
  const facts=[org.establishedYear && {label:'প্রতিষ্ঠার বছর',value:org.establishedYear},org.registrationInfo && {label:'নিবন্ধন তথ্য',value:org.registrationInfo}].filter(Boolean)
  return <section className="about-section"><div className="container who-grid"><div className="about-image-panel"><ImageWithFallback src={settings.branding?.banner} alt="সংগঠনের পরিচিতিমূলক দৃশ্য" className="who-image"/></div><div><p className="about-eyebrow">আমাদের পরিচয়</p><h2>আমরা কারা</h2><p className="about-lead">{description}</p>{facts.length>0 && <dl className="verified-facts">{facts.map(x=><div key={x.label}><dt>{x.label}</dt><dd>{x.value}</dd></div>)}</dl>}</div></div></section>
}
export function OurStory() { return <section className="about-section about-soft"><div className="container"><header className="about-heading"><p className="about-eyebrow">সম্মিলিত পথচলা</p><h2>আমাদের পথচলা</h2><p>কোনো অযাচাইকৃত সাল বা অর্জন নয়—মানবিক ভাবনা থেকে সংগঠিত সামাজিক উদ্যোগে এগিয়ে যাওয়ার ধারণাগত ধাপ।</p></header><ol className="story-timeline">{story.map(({title,icon:Icon},index)=><li key={title}><span className="story-number">০{index+1}</span><span className="story-icon"><Icon/></span><h3>{title}</h3></li>)}</ol></div></section> }
export function LocalConnection() { return <section className="about-section"><div className="container connection-grid"><div><p className="about-eyebrow">একই শেকড়, একই দায়বদ্ধতা</p><h2>দেশে ও প্রবাসে — একই বন্ধনে</h2><p className="about-lead">দেশে থাকা স্বেচ্ছাসেবক ও প্রবাসে থাকা বাকপুরাবাসীদের সহযোগিতা, যোগাযোগ ও সম্মিলিত উদ্যোগকে একটি সুসংগঠিত প্ল্যাটফর্মে যুক্ত করাই সংগঠনের অন্যতম লক্ষ্য।</p><div className="connection-tags"><span><UsersRound/> স্থানীয় জনগোষ্ঠী</span><span><Sprout/> যুবসমাজ</span><span><Globe2/> প্রবাসী সম্প্রদায়</span></div></div><div className="connection-symbol" aria-hidden="true"><span><UsersRound/></span><i/><span><Globe2/></span></div></div></section> }
export function WhyWeExist() { const themes=['দ্রুত মানবিক সহযোগিতা','সম্মিলিত উদ্যোগ','সংগঠিত যুবসমাজ','প্রবাসী ও স্থানীয়দের সংযোগ','দীর্ঘমেয়াদি সামাজিক উন্নয়ন']; return <section className="about-section why-section"><div className="container why-grid"><div><p className="about-eyebrow">প্রয়োজন থেকে প্রয়াস</p><h2>কেন এই সংগঠন</h2><p>মানুষের প্রয়োজনে দায়িত্বশীলভাবে পাশে দাঁড়ানো এবং বিচ্ছিন্ন সদিচ্ছাকে একটি সমন্বিত কল্যাণমুখী প্রয়াসে যুক্ত করার জন্য এই প্ল্যাটফর্ম।</p><Link className="text-link" to="/activities">কার্যক্রম দেখুন <ArrowRight size={17}/></Link></div><ul>{themes.map((x,i)=><li key={x}><span>০{i+1}</span>{x}</li>)}</ul></div></section> }
