import { Eye, HandHeart, Heart, Scale, ShieldCheck, Sparkles, Target, Users, Waypoints } from 'lucide-react'
import { Link } from 'react-router-dom'

const objectives=[['মানবিক সহায়তায় মানুষের পাশে দাঁড়ানো',HandHeart],['শিক্ষা ও সচেতনতামূলক উদ্যোগে সহায়তা করা',Sparkles],['স্বাস্থ্য ও জরুরি প্রয়োজনে সহযোগিতা করা',Heart],['যুবসমাজকে ইতিবাচক কাজে সম্পৃক্ত করা',Users],['স্থানীয় ও প্রবাসীদের মধ্যে সহযোগিতার সেতুবন্ধন তৈরি করা',Waypoints],['সামাজিক উন্নয়নমূলক উদ্যোগে সম্মিলিতভাবে কাজ করা',Target]]
const values=[['মানবতা','মানুষের মর্যাদা ও প্রয়োজনকে অগ্রাধিকার।',Heart],['ঐক্য','সম্মিলিত অংশগ্রহণ ও পারস্পরিক আস্থা।',Users],['স্বচ্ছতা','অনুমোদিত তথ্যের স্পষ্ট ও দায়িত্বশীল প্রকাশ।',Eye],['দায়িত্ববোধ','সিদ্ধান্ত ও কাজের প্রতি জবাবদিহি।',ShieldCheck],['সম্মান','সবার প্রতি মর্যাদাপূর্ণ আচরণ।',Scale],['সহযোগিতা','সাধারণ কল্যাণে একসঙ্গে এগিয়ে চলা।',HandHeart]]
export function MissionVision({ settings }) { const home=settings.homepage ?? {}; return <section className="about-section mission-section"><div className="container mission-grid"><article><span><Target/></span><p className="about-eyebrow">Mission</p><h2>আমাদের লক্ষ্য</h2><p>{home.mission || 'সমাজের অসহায় ও প্রয়োজনমতো মানুষের পাশে দাঁড়ানো, তরুণদের ইতিবাচক সামাজিক কর্মকাণ্ডে সম্পৃক্ত করা এবং স্থানীয় ও প্রবাসীদের সম্মিলিত অংশগ্রহণে কল্যাণমূলক উদ্যোগ বাস্তবায়ন করা।'}</p></article><article><span><Eye/></span><p className="about-eyebrow">Vision</p><h2>আমাদের স্বপ্ন</h2><p>{home.vision || 'সহযোগিতা, মানবিকতা, স্বচ্ছতা ও দায়িত্ববোধের মাধ্যমে একটি ঐক্যবদ্ধ ও উন্নত সমাজ গড়ে তোলা।'}</p></article></div></section> }
export function Objectives() { return <section className="about-section about-soft"><div className="container"><header className="about-heading centered"><p className="about-eyebrow">কাজের দিকনির্দেশনা</p><h2>আমাদের উদ্দেশ্য</h2></header><ul className="objective-grid">{objectives.map(([text,Icon])=><li key={text}><span><Icon/></span><p>{text}</p></li>)}</ul></div></section> }
export function CoreValues() { return <section className="about-section"><div className="container"><header className="about-heading"><p className="about-eyebrow">যে নীতিতে আমরা বিশ্বাস করি</p><h2>আমাদের মূল্যবোধ</h2></header><div className="value-grid">{values.map(([title,text,Icon])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section> }
export function Transparency() { return <section className="about-section transparency"><div className="container transparency-grid"><div><ShieldCheck/><p className="about-eyebrow">সুশৃঙ্খল ব্যবস্থাপনা</p><h2>স্বচ্ছতা ও দায়বদ্ধতা</h2><p>দায়িত্বশীল সিদ্ধান্ত, অনুমোদিত তথ্য প্রকাশ, ব্যক্তিগত তথ্যের গোপনীয়তা এবং অর্থ ও সহযোগিতার যথাযথ ব্যবস্থাপনা—আমাদের পরিচালনার গুরুত্বপূর্ণ নীতিগত ভিত্তি।</p><Link className="text-link" to="/privacy-policy">গোপনীয়তা নীতি</Link></div><ul><li>দায়িত্বশীল সিদ্ধান্ত</li><li>অনুমোদিত তথ্য প্রকাশ</li><li>ব্যক্তিগত তথ্যের গোপনীয়তা</li><li>সহযোগিতার যথাযথ ব্যবস্থাপনা</li><li>প্রশাসনিক কার্যক্রমের সুশৃঙ্খল রেকর্ড</li></ul></div></section> }
