import { MapPin, UserRound } from 'lucide-react'

function Avatar({ member, featured=false }){const [src,setSrc]=React.useState(member.photo?.url || member.photo || '');const alt=`${member.publicName} - ${member.positionBn || member.position || 'কমিটি সদস্য'}`;return src?<img src={src} onError={()=>setSrc('')} loading={featured?'eager':'lazy'} alt={alt}/>:<div className="committee-avatar-fallback" role="img" aria-label={`${alt} — ছবি নেই`}><UserRound/></div>}
import React from 'react'

export function CommitteeSelector({ committees, selected, onSelect }){if(committees.length<2)return null;return <section className="committee-selector"><div className="container"><span>কমিটি নির্বাচন করুন</span><div role="tablist" aria-label="প্রকাশিত কমিটি">{committees.map(item=><button type="button" role="tab" aria-selected={selected===item.slug} className={selected===item.slug?'is-selected':''} key={item.slug || item._id} onClick={()=>onSelect(item.slug)}>{item.nameBn || item.name}</button>)}</div></div></section>}
export function CommitteeIntro({ committee }){return <section className="committee-section"><div className="container committee-intro"><p className="committee-eyebrow">বর্তমান নির্বাচিত কমিটি</p><h2>{committee.nameBn || committee.name}</h2><p>{committee.descriptionBn || committee.description || 'সংগঠনের কার্যক্রম সমন্বয় ও মানবিক উদ্যোগে দায়িত্বশীল অংশগ্রহণের জন্য এই কমিটি কাজ করে।'}</p>{committee.term?.label&&<span>{committee.term.label}</span>}</div></section>}
function PersonCard({ member, featured=false }){return <article className={featured?'leader-card':'member-card'}><Avatar member={member} featured={featured}/><div><h3>{member.publicName}</h3><p className="member-position">{member.positionBn || member.position}</p>{member.publicLocation&&<p className="member-location"><MapPin size={14}/>{member.publicLocation}</p>}{featured&&member.shortBio&&<p className="member-bio">{member.shortBio}</p>}</div></article>}
export function LeadershipSection({ members }){const featured=members.filter(x=>x.isFeatured);if(!featured.length)return null;return <section className="committee-section leadership-section"><div className="container"><header className="committee-heading"><p className="committee-eyebrow">নেতৃত্ব</p><h2>কার্যনির্বাহী নেতৃত্ব</h2></header><div className="leadership-grid">{featured.map(x=><PersonCard key={x.id || x.publicName} member={x} featured/>)}</div></div></section>}
export function MembersGrid({ members, hasFeatured }){const list=members.filter(x=>!x.isFeatured);if(!list.length)return null;return <section className="committee-section members-section"><div className="container"><header className="committee-heading"><p className="committee-eyebrow">{hasFeatured?'কমিটির অন্যান্য সদস্য':'প্রকাশিত সদস্যবৃন্দ'}</p><h2>কমিটির সদস্যবৃন্দ</h2></header><div className="members-grid">{list.map(x=><PersonCard key={x.id || x.publicName} member={x}/>)}</div></div></section>}
