import { ArrowDown, ArrowRight, CalendarRange, Eye, Globe2, ListChecks, LockKeyhole, MessageCircle, ShieldCheck, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { formatBengaliDate } from '../../utils/formatDate'

const typeLabels={local:'স্থানীয় সদস্য',expatriate:'প্রবাসী সদস্য',youth:'যুব প্রতিনিধি',other:'অন্যান্য প্রতিনিধি'}
export function Representation({ members }){const entries=Object.entries(members.reduce((all,x)=>{if(x.memberType)all[x.memberType]=(all[x.memberType]||0)+1;return all},{}));if(!entries.length)return null;return <section className="committee-section"><div className="container"><header className="committee-heading centered"><p className="committee-eyebrow">সম্মিলিত প্রতিনিধিত্ব</p><h2>স্থানীয় ও প্রবাসীদের সংযোগ</h2></header><div className="representation-grid">{entries.map(([type,count])=><div key={type}>{type==='expatriate'?<Globe2/>:<UsersRound/>}<strong>{count.toLocaleString('bn-BD')}</strong><span>{typeLabels[type] || typeLabels.other}</span></div>)}</div></div></section>}
export function Structure({ members }){const positions=[...new Set(members.map(x=>x.positionBn||x.position).filter(Boolean))];if(!positions.length)return null;return <section className="committee-section committee-soft"><div className="container"><header className="committee-heading centered"><p className="committee-eyebrow">সাংগঠনিক বিন্যাস</p><h2>কমিটির কাঠামো</h2></header><div className="structure-flow"><span>নেতৃত্ব</span><ArrowDown/><div>{positions.slice(0,8).map(x=><span key={x}>{x}</span>)}</div><ArrowDown/><span>কমিটির সদস্যবৃন্দ</span></div></div></section>}
export function Responsibilities(){const items=['সংগঠনের কার্যক্রম সমন্বয়','মানবিক ও সামাজিক উদ্যোগে নেতৃত্ব','সদস্যদের মধ্যে যোগাযোগ ও সহযোগিতা','দায়িত্বশীল সিদ্ধান্ত গ্রহণ','স্বচ্ছতা ও জবাবদিহিতা বজায় রাখা'];return <section className="committee-section"><div className="container responsibilities-grid"><div><ListChecks/><p className="committee-eyebrow">সাধারণ নীতিগত দায়িত্ব</p><h2>দায়িত্ব ও ভূমিকা</h2><p>এগুলো সাধারণ সাংগঠনিক নীতি; কোনো অপ্রকাশিত সংবিধিবদ্ধ ক্ষমতার দাবি নয়।</p></div><ul>{items.map(x=><li key={x}><ShieldCheck/>{x}</li>)}</ul></div></section>}
export function CommitteeTerm({ term }){const start=formatBengaliDate(term?.startDate),end=formatBengaliDate(term?.endDate);if(!term?.label&&!start&&!end)return null;return <section className="committee-term"><div className="container"><CalendarRange/><div><p className="committee-eyebrow">প্রকাশিত মেয়াদ</p><h2>কমিটির মেয়াদ</h2><p>{term.label}</p>{(start||end)&&<span>{start}{start&&end?' — ':''}{end}</span>}</div></div></section>}
export function MessageAndPrivacy({ message }){return <><section className="leadership-message"><div className="container"><MessageCircle/><blockquote>“{message || 'ঐক্য, মানবিকতা ও দায়িত্ববোধের মাধ্যমে সমাজের কল্যাণে সম্মিলিতভাবে কাজ করাই আমাদের প্রত্যাশা।'}”</blockquote>{!message&&<p>— সংগঠনের সাধারণ বার্তা</p>}</div></section><section className="committee-section"><div className="container responsibility-panels"><article><Eye/><h2>স্বচ্ছতা ও দায়বদ্ধতা</h2><p>কমিটির দায়িত্ব পালনে ব্যক্তিগত গোপনীয়তা, দায়িত্বশীল সিদ্ধান্ত এবং সংগঠনের অনুমোদিত তথ্য প্রকাশের নীতিকে গুরুত্ব দেওয়া হয়।</p></article><article><LockKeyhole/><h2>সদস্যদের গোপনীয়তা</h2><p>এই পৃষ্ঠায় শুধুমাত্র জনসম্মুখে প্রকাশের জন্য অনুমোদিত কমিটি তথ্য প্রদর্শিত হয়। ব্যক্তিগত যোগাযোগ, পরিচয়পত্র, ঠিকানা বা অন্যান্য সংবেদনশীল তথ্য প্রকাশ করা হয় না।</p><Link className="text-link" to="/privacy-policy">গোপনীয়তা নীতি <ArrowRight size={16}/></Link></article></div></section></>}
