import { ArrowRight, BookOpen, HandHeart, HeartPulse, LifeBuoy, MapPin, Sprout, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import ImageWithFallback from '../common/ImageWithFallback'

const categories = [{label:'মানবিক সহায়তা',icon:HandHeart},{label:'শিক্ষা সহায়তা',icon:BookOpen},{label:'স্বাস্থ্য ও চিকিৎসা',icon:HeartPulse},{label:'যুব উন্নয়ন',icon:Sprout},{label:'সামাজিক কল্যাণ',icon:Users},{label:'জরুরি সহায়তা',icon:LifeBuoy}]
export function ActivityCategories() { return <section className="home-section soft-section"><div className="container"><header className="section-title centered"><p className="home-eyebrow">সেবার ক্ষেত্র</p><h2>আমাদের কার্যক্রম</h2><p>সমাজকল্যাণমূলক উদ্যোগের সম্ভাব্য প্রধান ক্ষেত্রসমূহ।</p></header><div className="category-grid">{categories.map(({label,icon:Icon})=><Link to="/activities" key={label}><span><Icon/></span><h3>{label}</h3></Link>)}</div><div className="section-action"><Link className="button button--outline home-button" to="/activities">সকল কার্যক্রম দেখুন</Link></div></div></section> }
export function FeaturedActivities({ items, loading }) { return <section className="home-section"><div className="container"><header className="section-title"><p className="home-eyebrow">সাম্প্রতিক উদ্যোগ</p><h2>নির্বাচিত কার্যক্রম</h2><p>প্রকাশিত কার্যক্রম থেকে নির্বাচিত কিছু উদ্যোগ।</p></header>{loading ? <Skeleton count={3}/> : items.length ? <div className="content-grid">{items.slice(0,3).map((x,i)=><article className="content-card" key={x._id || x.slug || i}><ImageWithFallback src={x.coverImage || x.image} alt={x.title || 'কার্যক্রমের ছবি'} className="card-image"/><div><span className="tag">{x.category?.name || x.category || 'কার্যক্রম'}</span><h3>{x.title}</h3>{x.summary && <p>{x.summary}</p>}{x.location && <small><MapPin size={14}/>{x.location}</small>}{x.slug && <Link className="text-link" to={`/activities/${x.slug}`}>বিস্তারিত <ArrowRight size={16}/></Link>}</div></article>)}</div> : <Empty text="প্রকাশিত নির্বাচিত কার্যক্রম বর্তমানে নেই।"/>}</div></section> }
export function CommunityHighlight() { return <section className="community"><div className="container"><p className="home-eyebrow">সম্মিলিত উদ্যোগ</p><h2>দেশে ও প্রবাসে, কল্যাণের বন্ধনে</h2><p>দেশে ও প্রবাসে থাকা বাকপুরাবাসীর সম্মিলিত প্রচেষ্টায় মানবিক ও সামাজিক কল্যাণে কাজ করার একটি প্ল্যাটফর্ম।</p></div></section> }
export function Skeleton({ count }) { return <div className="skeleton-grid" aria-label="তথ্য লোড হচ্ছে">{Array.from({length:count},(_,i)=><span key={i}/>)}</div> }
export function Empty({ text }) { return <p className="home-empty">{text}</p> }
