import { Clock3, ExternalLink, Mail, MapPin, Phone, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'

const clean=value=>typeof value==='string'?value.trim():''
const safeUrl=value=>{try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return''}}
const tel=value=>`tel:${value.replace(/[^+\d]/g,'')}`

export function ContactInfo({contact}){const address=[contact.address,contact.village,contact.upazila,contact.district,contact.country].map(clean).filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(', ');const cards=[];if(clean(contact.phone)||clean(contact.secondaryPhone))cards.push({icon:<Phone/>,title:'মোবাইল',body:[contact.phone,contact.secondaryPhone].map(clean).filter(Boolean).map(x=><a key={x} href={tel(x)}>{x}</a>)});if(clean(contact.email)||clean(contact.secondaryEmail))cards.push({icon:<Mail/>,title:'ইমেইল',body:[contact.email,contact.secondaryEmail].map(clean).filter(Boolean).map(x=><a key={x} href={`mailto:${x}`}>{x}</a>)});if(address)cards.push({icon:<MapPin/>,title:'ঠিকানা',body:<span>{address}</span>});if(clean(contact.officeHours))cards.push({icon:<Clock3/>,title:'অফিস সময়',body:<span>{contact.officeHours}</span>});return <>{cards.length>0&&<section className="contact-section"><div className="container"><header className="contact-heading"><p className="contact-eyebrow">সরাসরি যোগাযোগ</p><h2>যোগাযোগের তথ্য</h2></header><div className="contact-info-grid">{cards.map(card=><article key={card.title}>{card.icon}<div><h3>{card.title}</h3><p>{card.body}</p></div></article>)}</div></div></section>}{address&&<section className="contact-section contact-location"><div className="container"><MapPin/><div><p className="contact-eyebrow">ঠিকানা</p><h2>আমাদের অবস্থান</h2><p>{address}</p><small>এটি সংগঠনের প্রকাশিত ঠিকানা। নির্দিষ্ট map location কনফিগার করা না থাকায় কোনো অনুমানভিত্তিক মানচিত্র দেখানো হয়নি।</small></div></div></section>}{clean(contact.officeHours)&&<section className="contact-hours"><div className="container"><Clock3/><div><h2>যোগাযোগের সময়</h2><p>{contact.officeHours}</p></div></div></section>}</>}

export function PurposeGuide(){const items=[['সদস্যপদ','সদস্যপদ আবেদন ও সদস্য সংক্রান্ত প্রশ্ন'],['সহযোগিতা','অনুদান বা সহযোগিতা সংক্রান্ত তথ্য'],['কার্যক্রম','সামাজিক ও মানবিক কার্যক্রম সম্পর্কিত তথ্য'],['সাধারণ যোগাযোগ','অন্যান্য প্রশ্ন বা পরামর্শ']];return <section className="contact-section contact-guide"><div className="container"><header className="contact-heading"><h2>কোন বিষয়ে যোগাযোগ করবেন?</h2><p>ফর্মের উপযুক্ত ধরন নির্বাচন করলে বার্তাটি বুঝতে সুবিধা হবে।</p></header><div>{items.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>}

export function SocialLinks({social}){const sources=[['facebook','Facebook'],['youtube','YouTube'],['instagram','Instagram'],['whatsapp','WhatsApp'],['linkedin','LinkedIn']],links=sources.map(([key,label])=>({label,url:safeUrl(social?.[key])})).filter(x=>x.url);if(!links.length)return null;return <section className="contact-section social-section"><div className="container"><header className="contact-heading"><h2>সামাজিক মাধ্যমে যুক্ত থাকুন</h2></header><div>{links.map(({label,url})=><a key={label} href={url} target="_blank" rel="noopener noreferrer" aria-label={`${label}-এ সংগঠনের পেজ খুলুন`}><ExternalLink/>{label}</a>)}</div></div></section>}

export function ContactClosing({membershipEnabled}){const faqs=[['সদস্যপদ সম্পর্কে কীভাবে জানতে পারি?',<><Link to="/membership">সদস্যপদ পৃষ্ঠা</Link> দেখুন অথবা ফর্মে সদস্যপদ ধরন নির্বাচন করে বার্তা পাঠান।</>],['সহযোগিতা সম্পর্কে কোথায় যোগাযোগ করব?',<><Link to="/donation">সহযোগিতা পৃষ্ঠা</Link> দেখুন অথবা সহযোগিতা ধরনে বার্তা দিন।</>],['কার্যক্রমের তথ্য কোথায় পাওয়া যাবে?',<><Link to="/activities">কার্যক্রম পৃষ্ঠায়</Link> প্রকাশিত উদ্যোগগুলো দেখা যাবে।</>],['বার্তা পাঠানোর পর কী হবে?','বার্তাটি সংগঠনের দায়িত্বশীল প্রতিনিধির পর্যালোচনার জন্য থাকবে। নির্দিষ্ট উত্তর সময়ের নিশ্চয়তা দেওয়া হয় না।'],['আমার যোগাযোগের তথ্য কি প্রকাশ করা হবে?',<>যোগাযোগের তথ্য জনসম্মুখে প্রকাশ করা হয় না। বিস্তারিত <Link to="/privacy-policy">গোপনীয়তা নীতিতে</Link> দেখুন।</>]];return <><section className="contact-section contact-faq"><div className="container"><header className="contact-heading"><h2>সাধারণ প্রশ্ন</h2></header>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section><section className="contact-privacy"><div className="container"><ShieldCheck/><div><h2>আপনার তথ্যের গোপনীয়তা</h2><p>যোগাযোগ ফর্মে দেওয়া তথ্য জনসম্মুখে প্রকাশ করা হয় না এবং শুধুমাত্র প্রয়োজনীয় প্রশাসনিক যোগাযোগ ও পর্যালোচনার জন্য ব্যবহৃত হয়।</p><Link className="text-link" to="/privacy-policy">গোপনীয়তা নীতি দেখুন</Link></div></div></section><section className="contact-important"><div className="container"><strong>গুরুত্বপূর্ণ বার্তা</strong><p>জরুরি মানবিক বা গুরুত্বপূর্ণ বিষয়ে বার্তায় প্রয়োজনীয় তথ্য স্পষ্টভাবে উল্লেখ করুন। এই ফর্ম কোনো জরুরি সেবা বা হটলাইন নয়।</p></div></section><section className="contact-section"><div className="container contact-cta"><div><p className="contact-eyebrow">সংগঠনকে জানুন</p><h2>আমাদের সম্পর্কে আরও জানুন</h2></div><div><Link className="button button--primary" to="/about">আমাদের সম্পর্কে</Link><Link className="button button--outline" to="/activities">কার্যক্রম দেখুন</Link>{membershipEnabled&&<Link className="button button--gold" to="/membership">সদস্য হোন</Link>}</div></div></section></>}
