import { ArrowRight, ClipboardCheck, Eye, Globe2, HandHeart, HeartHandshake, Lightbulb, SearchCheck, ShieldCheck, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import ImageWithFallback from '../common/ImageWithFallback'
import { formatBengaliDate, scheduleState } from '../../utils/formatDate'

const focus=[['মানবিক সহযোগিতা',HandHeart],['স্বেচ্ছাসেবী অংশগ্রহণ',UsersRound],['সম্মিলিত উদ্যোগ',HeartHandshake],['সামাজিক দায়বদ্ধতা',ShieldCheck]]
const process=[['প্রয়োজন শনাক্তকরণ',SearchCheck],['পরিকল্পনা',Lightbulb],['সম্মিলিত সহযোগিতা',UsersRound],['বাস্তবায়ন',ClipboardCheck],['দায়বদ্ধতা ও পর্যালোচনা',Eye]]
export function ImpactAndProcess(){return <><section className="activity-impact"><div className="container"><header><p className="activities-eyebrow">সংখ্যার বাইরেও প্রভাব</p><h2>মানবিক মূল্যবোধে পরিচালিত উদ্যোগ</h2></header><div>{focus.map(([x,Icon])=><span key={x}><Icon/>{x}</span>)}</div></div></section><section className="activities-section"><div className="container"><header className="activities-heading centered"><p className="activities-eyebrow">সমন্বিত প্রক্রিয়া</p><h2>আমরা যেভাবে কাজ করি</h2></header><ol className="process-list">{process.map(([x,Icon],i)=><li key={x}><small>০{i+1}</small><span><Icon/></span><h3>{x}</h3></li>)}</ol></div></section></>}
export function Collaboration(){return <section className="collaboration-section"><div className="container"><div><p className="activities-eyebrow">একই লক্ষ্যে একসাথে</p><h2>স্থানীয় ও প্রবাসীদের সম্মিলিত উদ্যোগ</h2><p>স্থানীয় স্বেচ্ছাসেবক ও প্রবাসী বাকপুরাবাসীদের সহযোগিতা ও অংশগ্রহণকে একত্র করে সমাজকল্যাণমূলক উদ্যোগ বাস্তবায়নের একটি প্ল্যাটফর্ম হিসেবে সংগঠন কাজ করতে চায়।</p></div><div aria-hidden="true"><UsersRound/><i/><Globe2/></div></div></section>}
export function UpcomingActivities({ items }){const scheduled=items.filter(x=>scheduleState(x));if(!scheduled.length)return null;return <section className="activities-section upcoming-section"><div className="container"><header className="activities-heading"><p className="activities-eyebrow">সময়সূচি অনুযায়ী</p><h2>চলমান ও আসন্ন কার্যক্রম</h2></header><div>{scheduled.slice(0,4).map((x,i)=><Link to={x.slug?`/activities/${x.slug}`:'/activities'} key={x._id||i}><span>{scheduleState(x)==='upcoming'?'আসন্ন':'চলমান'}</span><h3>{x.titleBn||x.title}</h3>{formatBengaliDate(x.startDate)&&<small>{formatBengaliDate(x.startDate)}</small>}</Link>)}</div></div></section>}
export function ActivityGallery({ items }){const images=items.flatMap(x=>x.gallery||x.images||[]).map(x=>typeof x==='string'?{url:x}:x).filter(x=>(x.url||x.image)&&x.isPublic!==false&&x.active!==false&&(!x.status||x.status==='published')).slice(0,5);if(!images.length)return null;return <section className="activities-section"><div className="container"><header className="activities-heading-row"><div><p className="activities-eyebrow">কার্যক্রমের মুহূর্ত</p><h2>গ্যালারি প্রিভিউ</h2></div><Link className="text-link" to="/gallery">গ্যালারি দেখুন <ArrowRight size={17}/></Link></header><div className="activity-gallery">{images.map((x,i)=><ImageWithFallback key={x._id||i} src={x.url||x.image} alt={x.alt||x.caption||'কার্যক্রমের গ্যালারি ছবি'} className="activity-gallery-image"/>)}</div></div></section>}
export function TransparencyAndCTA({ activities, settings }){const safeUrl=value=>{try{return ['http:','https:'].includes(new URL(value).protocol)}catch{return false}};const reports=activities.filter(x=>safeUrl(x.publicReportUrl)).slice(0,3);return <><section className="activity-transparency"><div className="container"><ShieldCheck/><div><p className="activities-eyebrow">তথ্যের দায়িত্বশীল প্রকাশ</p><h2>স্বচ্ছতা ও দায়বদ্ধতা</h2><p>অনুমোদিত কার্যক্রমের তথ্য ও প্রকাশযোগ্য প্রতিবেদন যেখানে পাওয়া যায়, সেখানে জনসাধারণের জন্য তা উপস্থাপন করা হয়। ব্যক্তিগত বা প্রশাসনিক তথ্য প্রকাশ করা হয় না।</p>{reports.map(x=><a key={x._id||x.slug} href={x.publicReportUrl} target="_blank" rel="noreferrer">{x.resourceSummary||x.titleBn||x.title} <ArrowRight size={15}/></a>)}</div></div></section><section className="activities-section"><div className="container activities-cta"><div><p className="activities-eyebrow">সম্মিলিত কল্যাণে অংশ নিন</p><h2>সমাজের কল্যাণে আপনিও অংশ নিন</h2></div><div>{settings.membership?.applicationsEnabled!==false&&<Link className="button button--primary" to="/membership">সদস্য হোন</Link>}{settings.donation?.enabled!==false&&<Link className="button button--gold" to="/donation">সহযোগিতা করুন</Link>}<Link className="button button--outline" to="/contact">যোগাযোগ করুন</Link></div></div></section></>}
