import { BookOpen, HandHeart, HeartPulse, LifeBuoy, Search, SlidersHorizontal, Sprout, UsersRound } from 'lucide-react'

const categories=[['','সব কার্যক্রম'],['humanitarian','মানবিক সহায়তা'],['education','শিক্ষা'],['health','স্বাস্থ্য'],['social-welfare','সামাজিক কল্যাণ'],['emergency-relief','জরুরি সহায়তা'],['youth-development','যুব উন্নয়ন'],['community-development','কমিউনিটি উন্নয়ন'],['other','অন্যান্য']]
const focusAreas=[['humanitarian','মানবিক সহায়তা',HandHeart],['education','শিক্ষা সহায়তা',BookOpen],['health','স্বাস্থ্য ও চিকিৎসা',HeartPulse],['youth-development','যুব উন্নয়ন',Sprout],['emergency-relief','জরুরি সহায়তা',LifeBuoy],['community-development','সামাজিক ও কমিউনিটি উন্নয়ন',UsersRound]]
export default function ActivityFilters({ category, sort, search, onCategory, onSort, onSearch }) {
  return <section className="activity-filter-section" aria-labelledby="filter-title"><div className="container"><div className="filter-top"><div><p className="activities-eyebrow">অনুসন্ধান ও ফিল্টার</p><h2 id="filter-title">প্রকাশিত কার্যক্রম খুঁজুন</h2></div><form className="activity-search" onSubmit={event=>{event.preventDefault();onSearch(new FormData(event.currentTarget).get('search').trim())}}><label className="sr-only" htmlFor="activity-search">কার্যক্রম খুঁজুন</label><Search size={18}/><input id="activity-search" name="search" defaultValue={search} placeholder="কার্যক্রম খুঁজুন..."/><button type="submit">খুঁজুন</button></form><label className="sort-control"><SlidersHorizontal size={17}/><span className="sr-only">সাজানোর ধরন</span><select value={sort} onChange={event=>onSort(event.target.value)}><option value="recent">সাম্প্রতিক</option><option value="oldest">পুরোনো</option><option value="name">নাম অনুযায়ী</option></select></label></div><div className="category-filters" aria-label="কার্যক্রমের বিভাগ">{categories.map(([value,label])=><button type="button" key={label} className={category===value?'is-active':''} aria-pressed={category===value} onClick={()=>onCategory(value)}>{label}</button>)}</div></div></section>
}

export function ActivityAreas({ selected, onSelect }) { return <section className="activities-section activity-areas"><div className="container"><header className="activities-heading centered"><p className="activities-eyebrow">কাজের প্রধান ক্ষেত্র</p><h2>কল্যাণমূলক উদ্যোগের ক্ষেত্রসমূহ</h2><p>এগুলো সংগঠনের কার্যক্রমের সাধারণ ক্ষেত্র; সম্পন্ন প্রকল্পের দাবি নয়।</p></header><div>{focusAreas.map(([value,label,Icon])=><button type="button" key={value} className={selected===value?'is-selected':''} aria-pressed={selected===value} onClick={()=>onSelect(value)}><span><Icon/></span><strong>{label}</strong></button>)}</div></div></section> }
