import { ArrowRight, CalendarDays, MapPin, RefreshCw, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import ImageWithFallback from '../common/ImageWithFallback'
import { formatBengaliDate, scheduleState } from '../../utils/formatDate'

const titleOf=x=>x.titleBn || x.title
const categoryOf=x=>x.category?.nameBn || x.category?.name || x.category
export function ActivityCard({ item }) { const date=formatBengaliDate(item.startDate || item.publishedAt); const state=scheduleState(item); return <article className="activity-card"><ImageWithFallback src={item.coverImage?.url || item.coverImage || item.image} alt={titleOf(item) || 'কার্যক্রমের ছবি'} className="activity-card-image"/><div className="activity-card-body"><div className="activity-tags">{categoryOf(item)&&<span>{categoryOf(item)}</span>}{item.featured&&<span className="featured-tag"><Star size={12}/> নির্বাচিত</span>}{state&&<span className={`schedule-tag ${state}`}>{state==='upcoming'?'আসন্ন':'চলমান'}</span>}</div><h3>{titleOf(item)}</h3>{item.summary && <p>{item.summary}</p>}<div className="activity-meta">{date&&<span><CalendarDays size={15}/>{date}</span>}{item.location&&<span><MapPin size={15}/>{typeof item.location==='string'?item.location:item.location.name}</span>}</div>{item.slug&&<Link className="text-link" to={`/activities/${item.slug}`}>বিস্তারিত দেখুন <ArrowRight size={16}/></Link>}</div></article> }
export function FeaturedActivity({ item }) { if(!item)return null; const date=formatBengaliDate(item.startDate || item.publishedAt); return <section className="activities-section"><div className="container"><p className="activities-eyebrow">নির্বাচিত কার্যক্রম</p><article className="featured-activity"><ImageWithFallback src={item.coverImage?.url || item.coverImage || item.image} alt={titleOf(item) || 'নির্বাচিত কার্যক্রম'} className="featured-image"/><div><span className="activity-label">{categoryOf(item)||'কার্যক্রম'}</span><h2>{titleOf(item)}</h2>{item.summary&&<p>{item.summary}</p>}<div className="activity-meta">{date&&<span><CalendarDays size={15}/>{date}</span>}{item.location&&<span><MapPin size={15}/>{typeof item.location==='string'?item.location:item.location.name}</span>}</div>{item.slug&&<Link className="button button--primary home-button" to={`/activities/${item.slug}`}>বিস্তারিত দেখুন <ArrowRight size={17}/></Link>}</div></article></div></section> }
export function ActivitiesGrid({ items, loading, error, onRetry, onReset }) { return <section className="activities-section activities-list-section"><div className="container"><header className="activities-heading"><p className="activities-eyebrow">কার্যক্রমের তালিকা</p><h2>সকল কার্যক্রম</h2></header>{loading?<div className="activity-skeletons" aria-label="কার্যক্রম লোড হচ্ছে">{[1,2,3,4,5,6].map(x=><span key={x}/>)}</div>:error?<div className="activities-state"><h3>কার্যক্রম লোড করা যায়নি</h3><p>অনুগ্রহ করে কিছুক্ষণ পর আবার চেষ্টা করুন।</p><button className="button button--primary" onClick={onRetry}><RefreshCw size={17}/> আবার চেষ্টা করুন</button></div>:items.length?<div className="activities-grid">{items.map((x,i)=><ActivityCard item={x} key={x._id || x.slug || i}/>)}</div>:<div className="activities-state"><h3>এই ফিল্টারে কোনো কার্যক্রম পাওয়া যায়নি।</h3><button className="button button--outline" onClick={onReset}>সব কার্যক্রম দেখুন</button></div>}</div></section> }
export function Pagination({ page, pages, onPage }) { if(pages<=1)return null; const start=Math.max(1,page-2), end=Math.min(pages,page+2), numbers=Array.from({length:end-start+1},(_,i)=>start+i); return <nav className="activities-pagination" aria-label="কার্যক্রম পৃষ্ঠা"><button disabled={page<=1} onClick={()=>onPage(page-1)}>আগের</button>{numbers.map(x=><button key={x} className={x===page?'is-current':''} aria-current={x===page?'page':undefined} onClick={()=>onPage(x)}>{x.toLocaleString('bn-BD')}</button>)}<button disabled={page>=pages} onClick={()=>onPage(page+1)}>পরের</button></nav> }
