/* eslint-disable react-refresh/only-export-components */
import { ArrowRight, CirclePlay, RefreshCw } from 'lucide-react'
import { Link } from 'react-router-dom'
import { galleryCategoryLabels } from '../../constants/gallery'
import { formatBengaliDate } from '../../utils/formatDate'
import ImageWithFallback from '../common/ImageWithFallback'

export const mediaUrl=item=>item.url||item.imageUrl||item.image?.url||item.src
export const mediaTitle=item=>item.titleBn||item.title||item.caption
export const mediaAlt=item=>item.alt||mediaTitle(item)||'সংগঠনের গ্যালারি ছবি'
function MediaImage({item,className}){return <ImageWithFallback src={item.thumbnail?.url||item.thumbnail||mediaUrl(item)} alt={mediaAlt(item)} className={className}/>}
export function FeaturedGallery({items,onOpen}){if(!items.length)return null;return <section className="gallery-section featured-gallery"><div className="container"><header className="gallery-heading"><p className="gallery-eyebrow">নির্বাচিত গ্যালারি</p><h2>বিশেষ কিছু মুহূর্ত</h2></header><div className="featured-gallery-grid">{items.slice(0,5).map((x,i)=>x.mediaType==='video'?<a key={x._id||i} href={mediaUrl(x)} target="_blank" rel="noopener noreferrer" aria-label={`${mediaTitle(x)||'ভিডিও'} নতুন ট্যাবে খুলুন`}><MediaImage item={x} className="featured-media-image"/><CirclePlay/></a>:<button type="button" key={x._id||i} onClick={event=>onOpen(x,event.currentTarget)} aria-label={`${mediaAlt(x)} বড় করে দেখুন`}><MediaImage item={x} className="featured-media-image"/></button>)}</div></div></section>}
export function PhotoGallery({items,loading,error,onRetry,onReset,onOpen}){return <section className="gallery-section gallery-main"><div className="container"><header className="gallery-heading"><p className="gallery-eyebrow">ছবির গ্যালারি</p><h2>স্মরণীয় কিছু মুহূর্ত</h2></header>{loading&&items.length===0?<div className="gallery-skeletons">{[1,2,3,4,5,6].map(x=><span key={x}/>)}</div>:error?<div className="gallery-state"><h3>গ্যালারির তথ্য লোড করা যায়নি।</h3><button className="button button--primary" onClick={onRetry}><RefreshCw size={17}/> আবার চেষ্টা করুন</button></div>:items.length?<div className="photo-grid">{items.map((x,i)=><button type="button" key={x._id||i} onClick={event=>onOpen(x,event.currentTarget)} aria-label={`${mediaAlt(x)} বড় করে দেখুন`}><MediaImage item={x} className="gallery-photo"/><span>{mediaTitle(x)&&<strong>{mediaTitle(x)}</strong>}<small>{galleryCategoryLabels[x.category]||''}{formatBengaliDate(x.takenAt)&&<> · {formatBengaliDate(x.takenAt)}</>}</small></span></button>)}</div>:<div className="gallery-state"><h3>এই বিভাগে বর্তমানে কোনো ছবি বা ভিডিও প্রকাশিত হয়নি।</h3><button className="button button--outline" onClick={onReset}>সব দেখুন</button></div>}{loading&&items.length>0&&<p className="gallery-loading-more">আরও মিডিয়া লোড হচ্ছে…</p>}</div></section>}
export function VideoGallery({items}){if(!items.length)return null;return <section className="gallery-section video-gallery"><div className="container"><header className="gallery-heading"><p className="gallery-eyebrow">ভিডিও</p><h2>ভিডিও গ্যালারি</h2></header><div>{items.map((x,i)=><a key={x._id||i} href={mediaUrl(x)} target="_blank" rel="noopener noreferrer"><MediaImage item={x} className="video-thumbnail"/><CirclePlay/><span><strong>{mediaTitle(x)||'ভিডিও দেখুন'}</strong><small>নতুন ট্যাবে খুলবে</small></span></a>)}</div></div></section>}
export function GalleryLoadMore({page,pages,onMore}){if(page>=pages)return null;return <div className="gallery-load-more"><button className="button button--outline" onClick={()=>onMore(page+1)}>আরও দেখুন <ArrowRight size={17}/></button></div>}
export function RelatedActivity({item}){const activity=item?.relatedActivity;if(!activity?.slug||activity.isPublic===false||activity.status&&activity.status!=='published')return null;return <Link className="lightbox-activity" to={`/activities/${activity.slug}`}>সম্পর্কিত কার্যক্রম <ArrowRight size={15}/></Link>}
