import { AlertTriangle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { DonationHero, WhySupport } from '../../components/donation/DonationIntro'
import PaymentMethods from '../../components/donation/PaymentMethods'
import DonationForm from '../../components/donation/DonationForm'
import { DonationContact, DonationSuccess, OtherWaysAndFAQ, TransparencyPrivacy } from '../../components/donation/DonationClosing'
import PageLoader from '../../components/common/PageLoader'
import { donationPurposeLabels, paymentMethodLabels } from '../../constants/donation'
import { homeService, payload } from '../../services/homeService'
import '../../styles/donation-page.css'

export default function DonationPage(){const [settings,setSettings]=useState(null),[loadState,setLoadState]=useState('loading'),[success,setSuccess]=useState(null);useEffect(()=>{let current=true;homeService.settings().then(value=>{if(!current)return;setSettings(payload(value)||{});setLoadState('ready')}).catch(()=>{if(current)setLoadState('error')});return()=>{current=false}},[]);const donation=settings?.donation??{};const methods=useMemo(()=>Array.isArray(donation.paymentMethods)?donation.paymentMethods.filter(x=>x?.isEnabled===true&&paymentMethodLabels[x.type]).sort((a,b)=>(Number(a.displayOrder)||0)-(Number(b.displayOrder)||0)).map(x=>({id:x.id||x._id,type:x.type,label:x.label,accountName:x.accountName,accountNumber:x.accountNumber,instructions:x.instructions})):[],[donation.paymentMethods]);const currencies=useMemo(()=>Array.isArray(donation.supportedCurrencies)?donation.supportedCurrencies.filter(x=>typeof x==='string'&&/^[A-Z]{3}$/.test(x)):[],[donation.supportedCurrencies]);const purposes=useMemo(()=>{const supplied=donation.allowedPurposes||donation.supportedPurposes;return Array.isArray(supplied)?supplied.filter(x=>donationPurposeLabels[x]):Object.keys(donationPurposeLabels)},[donation.allowedPurposes,donation.supportedPurposes]);const defaultCurrency=currencies.includes(donation.defaultCurrency)?donation.defaultCurrency:currencies[0]||'';const enabled=loadState==='ready'&&donation.enabled===true&&methods.length>0&&currencies.length>0&&purposes.length>0;const config={methods,methodTypes:[...new Set(methods.map(x=>x.type))],currencies,purposes,defaultCurrency,minimumAmount:donation.minimumAmount,allowAnonymous:donation.allowAnonymous===true};return <><DonationHero banner={settings?.branding?.banner} enabled={enabled}/><WhySupport/>{loadState==='loading'&&<PageLoader label="সহযোগিতার সেটিংস লোড হচ্ছে…"/>}{loadState==='error'&&<section className="donation-unavailable"><AlertTriangle/><h2>সহযোগিতা ব্যবস্থা যাচাই করা যাচ্ছে না</h2><p>নিরাপত্তার কারণে সক্রিয় ফর্ম দেখানো হয়নি। পরে আবার চেষ্টা করুন।</p></section>}{loadState==='ready'&&donation.enabled!==true&&<section className="donation-unavailable"><AlertTriangle/><h2>অনলাইন সহযোগিতার তথ্য গ্রহণ সাময়িকভাবে বন্ধ</h2><p>{donation.publicMessage||'বর্তমানে অনলাইন সহযোগিতার তথ্য গ্রহণ সাময়িকভাবে বন্ধ রয়েছে।'}</p></section>}{loadState==='ready'&&donation.enabled===true&&<PaymentMethods methods={methods}/>} {loadState==='ready'&&donation.enabled===true&&!enabled&&<section className="donation-unavailable"><AlertTriangle/><h2>পেমেন্ট কনফিগারেশন অসম্পূর্ণ</h2><p>অনুমোদিত পেমেন্ট পদ্ধতি ও মুদ্রা প্রকাশিত হলে তথ্য জমা দেওয়া যাবে।</p></section>}{enabled&&(success?<DonationSuccess result={success}/>:<DonationForm config={config} onSuccess={setSuccess}/>)}<TransparencyPrivacy/><OtherWaysAndFAQ/><DonationContact/></>}
