import { AlertTriangle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { BenefitsAndTypes, GuidelinesAndProcess, MembershipHero } from '../../components/membership/MembershipIntro'
import MembershipForm from '../../components/membership/MembershipForm'
import { ApplicationSuccess, MembershipContact, MembershipFAQ, PrivacyAndNext } from '../../components/membership/MembershipClosing'
import PageLoader from '../../components/common/PageLoader'
import { membershipTypeLabels } from '../../constants/membership'
import { homeService, payload } from '../../services/homeService'
import '../../styles/membership.css'

export default function MembershipPage(){const [settings,setSettings]=useState(null),[loadState,setLoadState]=useState('loading'),[success,setSuccess]=useState(null);useEffect(()=>{let current=true;homeService.settings().then(value=>{if(!current)return;setSettings(payload(value)||{});setLoadState('ready')}).catch(()=>{if(current)setLoadState('error')});return()=>{current=false}},[]);const membership=settings?.membership??{},allowedTypes=useMemo(()=>Array.isArray(membership.allowedTypes)?membership.allowedTypes.filter(type=>membershipTypeLabels[type]):[],[membership.allowedTypes]),enabled=loadState==='ready'&&membership.applicationsEnabled===true&&allowedTypes.length>0,unsupported=membership.requireProfilePhoto===true||membership.requireIdentityVerification===true;const formSettings={allowedTypes,requirePhone:membership.requirePhone===true,requireEmail:membership.requireEmail===true};return <><MembershipHero banner={settings?.branding?.banner} enabled={enabled&&!unsupported}/><BenefitsAndTypes types={allowedTypes}/><GuidelinesAndProcess/>{loadState==='loading'&&<PageLoader label="সদস্যপদের সেটিংস লোড হচ্ছে…"/>}{loadState==='error'&&<section className="membership-unavailable"><AlertTriangle/><h2>আবেদন ব্যবস্থা যাচাই করা যাচ্ছে না</h2><p>নিরাপত্তার কারণে এই মুহূর্তে আবেদন ফর্ম চালু করা হয়নি। পরে আবার চেষ্টা করুন।</p></section>}{loadState==='ready'&&!membership.applicationsEnabled&&<section className="membership-unavailable"><AlertTriangle/><h2>সদস্যপদ আবেদন বর্তমানে বন্ধ</h2><p>{membership.applicationMessage||'বর্তমানে নতুন সদস্যপদ আবেদন গ্রহণ করা হচ্ছে না।'}</p></section>}{loadState==='ready'&&membership.applicationsEnabled&&allowedTypes.length===0&&<section className="membership-unavailable"><AlertTriangle/><h2>সদস্যপদের ধরন কনফিগার করা হয়নি</h2><p>অনুমোদিত সদস্যপদের ধরন প্রকাশিত হলে আবেদন করা যাবে।</p></section>}{enabled&&unsupported&&<section className="membership-unavailable"><AlertTriangle/><h2>আবেদন ফর্মে অতিরিক্ত যাচাই প্রয়োজন</h2><p>সেটিংসে ছবি বা পরিচয় যাচাই বাধ্যতামূলক, কিন্তু নিরাপদ পাবলিক আপলোড API নিশ্চিত নয়। তাই অনিরাপদ আপলোড তৈরি না করে ফর্ম বন্ধ রাখা হয়েছে।</p></section>}{enabled&&!unsupported&&(success?<ApplicationSuccess result={success}/>:<MembershipForm settings={formSettings} onSuccess={setSuccess}/>) }<PrivacyAndNext/><MembershipFAQ/><MembershipContact/></>}
