import { ArrowRight, BellRing, Info, Megaphone, Paperclip, Pin } from 'lucide-react'
import { Link } from 'react-router-dom'
import { newsTypeLabels } from '../../constants/news'
import { formatBengaliDate } from '../../utils/formatDate'

const title=x=>x.titleBn||x.title, date=x=>formatBengaliDate(x.publishedAt||x.createdAt)
export function NoticeBoard({items}){const notices=items.filter(x=>x.type==='notice');if(!notices.length)return null;return <section className="news-section"><div className="container"><header className="news-heading"><p className="news-eyebrow">দাপ্তরিক প্রকাশনা</p><h2>নোটিশ বোর্ড</h2></header><div className="notice-board">{notices.slice(0,6).map(x=><article key={x._id||x.slug}><BellRing/><div><h3>{title(x)}</h3><p>{date(x)}{(x.attachments||[]).some(a=>a.isPublic===true)&&<span><Paperclip size={13}/> সংযুক্তি আছে</span>}</p></div>{x.slug&&<Link to={`/news/${x.slug}`}><ArrowRight/></Link>}</article>)}</div></div></section>}
export function PinnedAndEvents({pinned,items}){const events=items.filter(x=>x.type==='event'||x.type==='announcement');if(!pinned.length&&!events.length)return null;return <section className="news-section news-secondary"><div className="container secondary-grid">{pinned.length>0&&<div><header className="news-heading"><Pin/><h2>পিন করা নোটিশ</h2></header>{pinned.slice(0,4).map(x=><Link key={x._id||x.slug} to={`/news/${x.slug}`}><span>{newsTypeLabels[x.type]||'প্রকাশনা'}</span><strong>{title(x)}</strong><small>{date(x)}</small></Link>)}</div>}{events.length>0&&<div><header className="news-heading"><Megaphone/><h2>ইভেন্ট ও ঘোষণা</h2></header>{events.slice(0,4).map(x=><Link key={x._id||x.slug} to={`/news/${x.slug}`}><span>{newsTypeLabels[x.type]}</span><strong>{title(x)}</strong><small>{x.eventDate&&<>ইভেন্ট: {formatBengaliDate(x.eventDate)} · </>}{date(x)}</small></Link>)}</div>}</div></section>}
export function PublicInfoAndCTA({settings}){return <><section className="news-public-info"><div className="container"><Info/><div><h2>জনসাধারণের জন্য প্রকাশিত তথ্য</h2><p>এই পৃষ্ঠায় শুধুমাত্র জনসাধারণের জন্য অনুমোদিত সংবাদ, ঘোষণা ও নোটিশ প্রকাশ করা হয়।</p><Link className="text-link" to="/privacy-policy">গোপনীয়তা নীতি <ArrowRight size={15}/></Link></div></div></section><section className="news-section"><div className="container news-cta"><div><p className="news-eyebrow">হালনাগাদ থাকুন</p><h2>সংগঠনের সর্বশেষ তথ্যের সাথে যুক্ত থাকুন</h2></div><div><Link className="button button--primary" to="/activities">আমাদের কার্যক্রম</Link><Link className="button button--outline" to="/contact">যোগাযোগ করুন</Link>{settings.membership?.applicationsEnabled!==false&&<Link className="button button--gold" to="/membership">সদস্য হোন</Link>}</div></div></section></>}
