import { ArrowRight, CalendarDays, Paperclip, Pin, RefreshCw, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { newsTypeLabels } from '../../constants/news'
import { formatBengaliDate } from '../../utils/formatDate'
import ImageWithFallback from '../common/ImageWithFallback'

const title=x=>x.titleBn||x.title, published=x=>formatBengaliDate(x.publishedAt||x.publishDate||x.createdAt), publicAttachments=x=>(x.attachments||[]).filter(a=>a?.isPublic===true)
export function NewsCard({item}){return <article className="news-card"><ImageWithFallback src={item.featuredImage?.url||item.featuredImage||item.image} alt={title(item)||'সংবাদের ছবি'} className="news-card-image"/><div><div className="news-tags"><span>{newsTypeLabels[item.type]||'প্রকাশনা'}</span>{item.isPinned&&<span><Pin size={12}/> পিন করা</span>}{item.isFeatured&&<span><Star size={12}/> নির্বাচিত</span>}</div><h3>{title(item)}</h3>{item.summary&&<p>{item.summary}</p>}<div className="news-meta">{published(item)&&<span><CalendarDays size={14}/>{published(item)}</span>}{publicAttachments(item).length>0&&<span><Paperclip size={14}/>সংযুক্তি আছে</span>}</div>{item.slug&&<Link className="text-link" to={`/news/${item.slug}`}>বিস্তারিত পড়ুন <ArrowRight size={16}/></Link>}</div></article>}
export function ImportantNotices({items}){if(!items.length)return null;return <section className="important-notices"><div className="container"><header><p className="news-eyebrow">জরুরি প্রকাশনা</p><h2>গুরুত্বপূর্ণ নোটিশ</h2></header><div>{items.slice(0,3).map(x=><article key={x._id||x.slug}><span>{newsTypeLabels[x.type]||'নোটিশ'}</span><div><h3>{title(x)}</h3>{published(x)&&<small>{published(x)}</small>}</div>{x.slug&&<Link to={`/news/${x.slug}`} aria-label={`${title(x)} বিস্তারিত`}><ArrowRight/></Link>}</article>)}</div></div></section>}
export function FeaturedNews({item}){if(!item)return null;return <section className="news-section"><div className="container"><p className="news-eyebrow">নির্বাচিত প্রকাশনা</p><article className="featured-news"><ImageWithFallback src={item.featuredImage?.url||item.featuredImage||item.image} alt={title(item)||'নির্বাচিত সংবাদ'} className="featured-news-image"/><div><span>{newsTypeLabels[item.type]||'প্রকাশনা'}</span><h2>{title(item)}</h2>{item.summary&&<p>{item.summary}</p>}{published(item)&&<small><CalendarDays size={15}/>{published(item)}</small>}{item.slug&&<Link className="button button--primary" to={`/news/${item.slug}`}>বিস্তারিত পড়ুন <ArrowRight size={17}/></Link>}</div></article></div></section>}
export function NewsGrid({items,loading,error,onRetry,onReset}){return <section className="news-section latest-news-section"><div className="container"><header className="news-heading"><p className="news-eyebrow">সর্বশেষ প্রকাশনা</p><h2>সর্বশেষ সংবাদ</h2></header>{loading?<div className="news-skeletons">{[1,2,3,4,5,6].map(x=><span key={x}/>)}</div>:error?<div className="news-state"><h3>তথ্য লোড করা যায়নি</h3><p>আবার চেষ্টা করুন।</p><button className="button button--primary" onClick={onRetry}><RefreshCw size={17}/> আবার চেষ্টা করুন</button></div>:items.length?<div className="news-grid">{items.map(x=><NewsCard key={x._id||x.slug} item={x}/>)}</div>:<div className="news-state"><h3>কোনো সংবাদ বা নোটিশ পাওয়া যায়নি।</h3><button className="button button--outline" onClick={onReset}>সব দেখুন</button></div>}</div></section>}
export function Pagination({page,pages,onPage}){if(pages<=1)return null;const start=Math.max(1,page-2),end=Math.min(pages,page+2);return <nav className="news-pagination" aria-label="সংবাদ পৃষ্ঠা"><button disabled={page<=1} onClick={()=>onPage(page-1)}>আগের</button>{Array.from({length:end-start+1},(_,i)=>start+i).map(x=><button key={x} className={x===page?'current':''} aria-current={x===page?'page':undefined} onClick={()=>onPage(x)}>{x.toLocaleString('bn-BD')}</button>)}<button disabled={page>=pages} onClick={()=>onPage(page+1)}>পরের</button></nav>}
