import { ArrowUpRight, Database, Server, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'

const date=value=>value?new Intl.DateTimeFormat('bn-BD',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const role=value=>({'super-admin':'Super Admin','management-admin':'Management Admin','finance-admin':'Finance Admin','content-admin':'Content Admin'}[value]||value)
export function RecentMembers({source}){return <article className="dashboard-panel"><header><h2>সাম্প্রতিক সদস্য</h2><Link to="/admin/members">সকল সদস্য →</Link></header>{source.status==='loading'&&<p className="dashboard-loading">তথ্য লোড হচ্ছে…</p>}{source.status==='error'&&<p className="dashboard-error">সদস্যের তথ্য লোড করা যায়নি।</p>}{source.status==='ready'&&(source.data?.length?<div className="dashboard-list">{source.data.map(member=><Link key={member.id||member._id} to={`/admin/members/${member.id||member._id}`}><span><strong>{member.fullName}</strong><small>{member.memberId||'আইডি নেই'} · {member.membership?.type||'সাধারণ'}</small></span><span>{member.status}</span></Link>)}</div>:<p className="dashboard-empty">কোনো সদস্য নেই</p>)}</article>}
export function FinanceOverview({stats,summary}){return <article className="dashboard-panel finance-panel"><header><h2>অর্থের সারসংক্ষেপ</h2><Link to="/admin/finance">অর্থ ব্যবস্থাপনা →</Link></header>{(stats.status==='loading'||summary.status==='loading')&&<p className="dashboard-loading">আর্থিক তথ্য লোড হচ্ছে…</p>}{(stats.status==='error'||summary.status==='error')&&<p className="dashboard-error">সম্পূর্ণ আর্থিক সারসংক্ষেপ পাওয়া যায়নি।</p>}{stats.status==='ready'&&<div className="finance-pending"><span>অপেক্ষমাণ লেনদেন <strong>{stats.data.pendingTransactions}</strong></span><span>অপেক্ষমাণ সহযোগিতা <strong>{stats.data.pendingDonations}</strong></span></div>}{summary.status==='ready'&&(Object.keys(summary.data||{}).length?<div className="currency-grid">{Object.entries(summary.data).map(([currency,total])=><section key={currency}><h3>{currency}</h3><p><span>আয়</span><strong>{total.income}</strong></p><p><span>ব্যয়</span><strong>{total.expense}</strong></p><p><span>ভারসাম্য</span><strong>{total.balance}</strong></p><div className="finance-bars" aria-label={`${currency} আয় ও ব্যয়ের তুলনা`}><i style={{width:`${Math.max(4,Number(total.income)>=Number(total.expense)?100:Number(total.income)/Math.max(Number(total.expense),1)*100)}%`}}/><i className="expense" style={{width:`${Math.max(4,Number(total.expense)>=Number(total.income)?100:Number(total.expense)/Math.max(Number(total.income),1)*100)}%`}}/></div></section>)}</div>:<p className="dashboard-empty">অনুমোদিত আর্থিক সারসংক্ষেপ নেই</p>)}</article>}
export function QuickActions({permissions}){const actions=[['members.create','নতুন সদস্য যোগ','/admin/members'],['applications.view','সদস্যপদ আবেদন দেখুন','/admin/membership-applications'],['activities.create','নতুন কার্যক্রম','/admin/activities'],['news.create','সংবাদ প্রকাশ','/admin/news'],['gallery.upload','গ্যালারি ব্যবস্থাপনা','/admin/gallery'],['finance.create','লেনদেন যোগ','/admin/finance'],['documents.upload','ডকুমেন্ট যোগ','/admin/documents'],['settings.manage','Settings','/admin/settings']].filter(([permission])=>permissions.has(permission));if(!actions.length)return null;return <article className="dashboard-panel quick-actions"><h2>দ্রুত কাজ</h2><div>{actions.map(([,label,to])=><Link key={label} to={to}>{label}<ArrowUpRight/></Link>)}</div></article>}
export function AuditActivity({source}){return <article className="dashboard-panel"><header><h2>সাম্প্রতিক প্রশাসনিক কার্যক্রম</h2></header>{source.status==='loading'&&<p className="dashboard-loading">কার্যক্রম লোড হচ্ছে…</p>}{source.status==='error'&&<p className="dashboard-error">কার্যক্রমের তথ্য পাওয়া যায়নি।</p>}{source.status==='ready'&&(source.data?.length?<div className="audit-list">{source.data.map(item=><div key={item._id}><strong>{item.actor?.fullName||item.actor?.username||'Admin'}</strong><span>{item.description||String(item.action||'কার্যক্রম').replaceAll('.',' · ')}</span><small>{date(item.createdAt)}</small></div>)}</div>:<p className="dashboard-empty">কোনো সাম্প্রতিক কার্যক্রম নেই</p>)}</article>}
export function AccountAndSystem({admin,health}){return <div className="account-system"><article className="dashboard-panel"><ShieldCheck/><h2>অ্যাকাউন্ট ও নিরাপত্তা</h2><p><strong>{admin.fullName||admin.username}</strong></p><p>{role(admin.role)} · {admin.status}</p><small>সর্বশেষ লগইন: {date(admin.lastLoginAt)}</small></article><article className="dashboard-panel"><Server/><h2>সিস্টেম অবস্থা</h2>{health.status==='loading'&&<p>যাচাই হচ্ছে…</p>}{health.status==='error'&&<p className="dashboard-error">সার্ভারের অবস্থা যাচাই করা যায়নি।</p>}{health.status==='ready'&&<><p><Server/> Server — সচল</p><p><Database/> Database — {health.data.database==='connected'?'সংযুক্ত':health.data.database}</p></>}</article></div>}
